---

- name: Install R packages from repositories (binary format)
  apt:
    name: "{{r_cran_pkgs}}"
    state: latest
  when: r_cran_pkgs is defined
  
- name: Install R packages from BioConductor (source format)
  command: "/usr/lib/R/site-library/littler/examples/installBioc.r {{ r_bioc_pkgs | join(' ') }}"
  when: r_bioc_pkgs is defined

- name: Install R packages from Github (source format)
  command: "/usr/lib/R/site-library/littler/examples/installGithub.r {{ r_github_pkgs | join(' ') }}"
  when: r_github_pkgs is defined

- name: Install R packages from repositories (source format)
  command: "/usr/lib/R/site-library/littler/examples/install.r {{ r_src_pkgs | join(' ') }}"
  when: r_src_pkgs is defined

