---

- set_fact:
    r_install:
      - r-recommended
      - r-base-dev
      - r-cran-rcpp
      - r-cran-devtools
      - r-cran-biocmanager
      - r-cran-rcurl
      - r-cran-base64enc
      - r-cran-mime
      - r-cran-inline
      - r-cran-docopt
      - r-cran-littler

- name: Install R along with some useful packages
  apt:
    name: "{{ r_install }}"
    state: latest
  when: r_install is defined
