---

- set_fact:
    r_kernel_pkgs:
      - pbdZMQ
      - IRdisplay
      - IRkernel

- name: Install IR Kernel packages from source
  command: "/usr/lib/R/site-library/littler/examples/install.r {{ r_kernel_pkgs | join(' ') }}"
  when: r_kernel_pkgs is defined

- name: Create symbolic link for R
  file:
    src: "/usr/lib/R"
    dest: "/opt/tljh/user/lib/R"
    state: link

- name: Create symbolic link for Jupyter
  file:
    src: "/opt/tljh/user/bin/jupyter"
    dest: "/usr/bin/jupyter"
    state: link

- name: Link IR kernel to Jupyterhub
  command: '/usr/bin/R -e "IRkernel::installspec(user = FALSE)"'
  register: irkernel



